name: 'Release Please'

on:
    push:
        branches: ['release-test']

permissions:
    # This job has the highest privileges, so always pin actions to a specific commit hash.
    # Ensure the referenced commit hash is verified and free from known vulnerabilities.
    id-token: write # Required for OIDC (npm release)
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            # The logic below handles the npm publication:
            - uses: actions/checkout@v6
              # these if statements ensure that a publication only occurs when
              # a new release is created:

            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Publish to NPM
              run: npm publish --access public
